name: linux-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  OS_VERSION: ubuntu-latest

jobs:
  chrome:
    uses: ./.github/workflows/chrome.yml
    with:
      os-version: ${{ env.OS_VERSION }}

  mkcert:
    uses: ./.github/workflows/mkcert.yml
    with:
      os-version: ${{ env.OS_VERSION }}
