name: linux-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/chrome@main

  mkcert:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/go@main
      - uses: ./actions/mkcert@main

  pebble:
    runs-on: ubuntu-latest
    steps:
      - uses: ./actions/go@main
      - uses: ./actions/pebble@main
