name: macos-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go:
    uses: ./.github/workflows/go-action.yml
    with:
      os-version: macos-latest

  #chrome:
  #  uses: ./.github/workflows/chrome.yml
  #  with:
  #    os-version: macos-latest

  #mkcert:
  #  needs: go
  #  uses: ./.github/workflows/mkcert.yml
  #  with:
  #    os-version: macos-latest

  pebble:
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/go.yml
      - uses: ./.github/workflows/pebble.yml
