name: macos-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  OS_VERSION: macos-latest

jobs:
  init-chrome:
    uses: ./.github/workflows/init-chrome.yml
    with:
      os-version: ${{ env.OS_VERSION }}

  mkcert:
    uses: ./.github/workflows/mkcert.yml
    with:
      os-version: ${{ env.OS_VERSION }}
