name: mkcert

on:
  workflow_call:
    inputs:
      os-version:
        type: string
        default: ubuntu-latest

jobs:
  mkcert:
    runs-on: ${{ inputs.os-version }}

    steps:
      - name: mkcert requirements for Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install -y libnss3-tools

      - name: build and run mkcert macos and Linux
        if: ${{ runner.os == 'macos'  || runner.os == 'Linux' }}
        working-directory: ${{ runner.temp }}
        run: |
          go install filippo.io/mkcert@latest
          mkcert -install

      - name: build and run mkcert Windows
        if: ${{ runner.os == 'Windows' }}
        working-directory: ${{ runner.temp }}
        shell: pwsh
        run: |
          choco install mkcert
          Start-Process mkcert -Wait -ArgumentList "-install" -Verb RunAs
