name: windows-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  chrome:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go
      - uses: ./.github/actions/chrome

  mkcert:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go
      - uses: ./.github/actions/mkcert

  pebble:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/go
      - uses: ./.github/actions/pebble
