name: windows-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  OS_VERSION: windows-latest

jobs:
  go:
    uses: ./.github/workflows/go.yml
    with:
      os-version: ${{ env.OS_VERSION }}

  chrome:
    uses: ./.github/workflows/chrome.yml
    with:
      os-version: ${{ env.OS_VERSION }}

  mkcert:
    needs: go
    uses: ./.github/workflows/mkcert.yml
    with:
      os-version: ${{ env.OS_VERSION }}

  pebble:
    needs: go
    uses: ./.github/workflows/pebble.yml
    with:
      os-version: ${{ env.OS_VERSION }}
