name: windows-setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go:
    uses: ./.github/workflows/go.yml
    with:
      os-version: windows-latest

  chrome:
    uses: ./.github/workflows/chrome.yml
    with:
      os-version: windows-latest

  mkcert:
    needs: go
    uses: ./.github/workflows/mkcert.yml
    with:
      os-version: windows-latest

  pebble:
    needs: go
    uses: ./.github/workflows/pebble.yml
    with:
      os-version: windows-latest
